### ISSUE TITLE
taimen (Pixel 2 XL) support

### ISSUE THREAD

**Issue by thestinger** [anestisb/android-prepare-vendor#109]
Google posted the factory images, but I don't have one yet and I plan on waiting a bit longer: https://developers.google.com/android/images#taimen.

**Comment by anestisb** [comment]
An initial attempt is under review / testing in https://github.com/anestisb/android-prepare-vendor/pull/115

Additional testers are more than welcome.

**Comment by anestisb** [comment]
A few people have contacted me that they tested the configs with no major issues so far. Closing since initial support is considered completed.
