### ISSUE TITLE
Nexus Player support

### ISSUE THREAD

**Issue by kyvaith** [anestisb/android-prepare-vendor#113]
Hi,

Could You please extend your support for Nexus Player (figure)?

Thanks.

**Comment by anestisb** [comment]
I don't have a Nexus Player device or have worked at all with this device. I'm guessing despite the different CPU arch, the configs approach should be identical.

I don't plan to provide support for this device. If you want you can start drafting the template configs and I can help along the process to iron them out. However, I don't have the capacity at the moment to do any kind of testing against the configs.

**Comment by thestinger** [comment]
It's already end-of-life too, the last release was November 2017.

**Comment by mydongistiny** [comment]
@kyvaith If you wanted to make a config you can start by basing it off of https://review.lineageos.org/#/c/207635/
