### ISSUE TITLE
wahoo_gfxdrv should have LOCAL_DEX_PREOPT forced to false

### ISSUE THREAD

**Issue by thestinger** [anestisb/android-prepare-vendor#118]
It doesn't have any code so it breaks in CopperheadOS without that, since it enables preopt for vendor unlike AOSP. It just needs `LOCAL_DEX_PREOPT := false` forced like what's already done for the theme overlay apks.

**Comment by anestisb** [comment]
I can add some logic to the vendor generate script to annotate all archives without a bytecode file as  `LOCAL_DEX_PREOPT := false`. That would be less painful than maintaining more exceptions manually.

I think that should work for your case too.

**Comment by anestisb** [comment]
Done in https://github.com/anestisb/android-prepare-vendor/commit/d1de4a8636e0c18b08b74f74067197703ef19c07

**Comment by thestinger** [comment]
Yeah, that should work well.
