### ISSUE TITLE
add vendor to AB_OTA_PARTITIONS for taimen / walleye just like marlin / sailfish

### ISSUE THREAD

**Issue by thestinger** [anestisb/android-prepare-vendor#119]
It's missing so OTA updates result in a broken installation since they don't include vendor.img

**Comment by thestinger** [comment]
Yeah, this makes OTA updates work. I just edited the generated output for now though.

**Comment by anestisb** [comment]
Ok done in https://github.com/anestisb/android-prepare-vendor/commit/80b599405cea3aedf78e1356ec95e93526ecf445.
