### ISSUE TITLE
TMPDIR too small -- override necessary

### ISSUE THREAD

**Issue by Rudd-O** [anestisb/android-prepare-vendor#129]
```
readonly TMP_WORK_DIR=$(mktemp -d /tmp/android_prepare_vendor.XXXXXX)
```
That should use $TMPDIR and fall back to /tmp if not set.

Most platforms mount a very limited ramfs /tmp nowadays.  This causes builds to fail.  Overriding this via the standard variable TMPDIR is the right thing to do.

**Comment by Rudd-O** [comment]
Same goes for `scripts/extract-factory-images.sh`.

**Comment by anestisb** [comment]
Yup, will do across the border.

**Comment by anestisb** [comment]
Done in https://github.com/anestisb/android-prepare-vendor/commit/b969a3237f7a5bb31b14306b7b9222d4f7a48c2f. Let me know if you still have issues.
