### ISSUE TITLE
CDEX framework & Apk files

### ISSUE THREAD

**Issue by anestisb** [anestisb/android-prepare-vendor#130]
The following framework Jar are present in Android Pie images, although are not present in AOSP.

* marlin/sailfish:
  * system/framework/PowerAnomalyDataModemInterface.jar
  * system/framework/PowerAnomalyStub.jar
  * system/product/app/SSRestartDetector/SSRestartDetector.apk
* walleye/taimen:
  * system/framework/libhwinfo.jar
  * system/framework/vendor.qti.qcril.am-V1.0-java.jar
  * system/framework/PowerAnomalyDataModemInterface.jar
  * system/framework/PowerAnomalyStub.jar
  * system/product/app/SSRestartDetector/SSRestartDetector.apk

So far all missing framework Jar were inserted in naked config. Adding them is postponed until the CDEX issue is resolved.

**Comment by anestisb** [comment]
Same for "system/product/app/SSRestartDetector/SSRestartDetector.apk"

**Comment by anestisb** [comment]
The oatdump [patch](https://gist.github.com/anestisb/26ecf8ae13746dc476eddd8d04a5dd23) and the standalone [utility](https://gist.github.com/anestisb/30265097ad9a5ea2f0ddf7e36db3f07d) are stable enough for testing. I'll probably proceed with the oatdump approach since I'm already compiling for the distribution.

Testing is scheduled for the next couple of days.

**Comment by dan-v** [comment]
Thanks for the update @anestisb

**Comment by anestisb** [comment]
Cdex support has been added via an oatdump patch. Latest revision of the patch is available [here](https://gist.github.com/anestisb/26ecf8ae13746dc476eddd8d04a5dd23). Will upstream the code to AOSP so that I don't need to maintain it independently.

**Comment by anestisb** [comment]
Missing bytecode files have been added to the corresponding device configs.
