### ISSUE TITLE
Script could fail earlier if ext4fuse is missing

### ISSUE THREAD

**Issue by kuleszdl** [anestisb/android-prepare-vendor#133]
First of all, many thanks for making the useful scripts available!

I noticed a minor issue: The script does not check whether ext4fuse is available before extracting starts but fails afterwards:

```
    ...

[*] Using ext4fuse for image mounts
[*] Extracting '/android/android-prepare-vendor/x/sailfish/ppr2.180905.006/sailfish-ppr2.180905.006-factory-bad3cb18.zip'
[*] Unzipping 'image-sailfish-ppr2.180905.006.zip'
[-] '/tmp/android_img_extract.kU5l1f/sailfish-ppr2.180905.006-factory-bad3cb18/images/system.img.raw' mount failed
/android/android-prepare-vendor/scripts/extract-factory-images.sh: Zeile 129: ext4fuse: Kommando nicht gefunden.
[-] Factory images data extract failed
```

This could be enhanced by checking for the presense of the `ext4fuse` binary earlier, because after installting ext4fuse the unzip process needs to be re-run.

**Comment by anestisb** [comment]
Xmm weird, it should be already handled in https://github.com/anestisb/android-prepare-vendor/blob/master/scripts/extract-factory-images.sh#L258

Are you running in macOS or Linux host?

**Comment by kuleszdl** [comment]
I am running on a Linux host.

**Comment by anestisb** [comment]
Ok found it. Should be fixed in https://github.com/anestisb/android-prepare-vendor/commit/9b2c17ee35a505240c5befdba5b8b98a262b791e. Switching languages within the same project results to bad patterns :)

Thanks for reporting.

**Comment by kuleszdl** [comment]
Cool, many thanks!
