### ISSUE TITLE
vendor gets added as a radio image

### ISSUE THREAD

**Issue by thestinger** [anestisb/android-prepare-vendor#148]
e25cdf271b33c50dfa64c7f86beff04c60b726dd results in vendor.img being added as a radio image rather than just adding it to AB_OTA_PARTITIONS.

**Comment by thestinger** [comment]
I linked to the wrong commit, I meant e25cdf271b33c50dfa64c7f86beff04c60b726dd.

**Comment by anestisb** [comment]
Reverted https://github.com/anestisb/android-prepare-vendor/commit/66cef8748c5fc85d55f93b0ed0b3e94f372e2e88 and placed a comment in https://github.com/anestisb/android-prepare-vendor/commit/5e064754f880978b27e88680adb4153b410e068c to avoid same mistake. Thanks.

**Comment by thestinger** [comment]
Resolved.
