### ISSUE TITLE
Setup wizard 

### ISSUE THREAD

**Issue by respinout** [anestisb/android-prepare-vendor#154]
Is it intended to not have the Setup Wizard on first boot?

**Comment by thestinger** [comment]
The real Setup Wizard is part of Play Services and requires setting it up properly. It isn't part of AOSP.

**Comment by thestinger** [comment]
The stock Setup Wizard is part of Play Services and requires setting it up properly. It isn't part of AOSP, and in general vendors and alternative operating systems provide their own.

**Comment by respinout** [comment]
Understood, thank you
