### ISSUE TITLE
cannot verify dl.google.com's certificate

### ISSUE THREAD

**Issue by iftaziz** [anestisb/android-prepare-vendor#168]
[*] Downloading image from 'https://dl.google.com/dl/android/aosp/walleye-opm2.171019.029-factory-41296266.zip'
--2019-07-29 15:24:34--  https://dl.google.com/dl/android/aosp/walleye-opm2.171019.029-factory-41296266.zip
Resolving dl.google.com (dl.google.com)... 216.58.207.14, 2a00:1450:4019:803::200e
Connecting to dl.google.com (dl.google.com)|216.58.207.14|:443... connected.
ERROR: cannot verify dl.google.com's certificate, issued by ‘CN=Google Internet Authority G3,O=Google Trust Services,C=US’:
  Unable to locally verify the issuer's authority.
To connect to dl.google.com insecurely, use `--no-check-certificate'.
[-] Images download failed

**Comment by anestisb** [comment]
Maybe Google was rotating certificates or hit a infra on an interim state. Cannot reproduce atm. Please reopen if you still face the issue with your environment.
