### ISSUE TITLE
"There's an internal problem with your device." dialog was shown in my Nexus 5x with 7.0

### ISSUE THREAD

**Issue by k3vinlusec** [anestisb/android-prepare-vendor#41]
I used this tool to build AOSP Nougat 7.0 on my Nexus 5x,  it seems that it works. But  when I restart the device each time, there is a dialog like "There's an internal problem with your device...." shown in the screen.  I'm not sure if there's a bug in this tool.

**Comment by anestisb** [comment]
You're probably having the same issue as https://github.com/anestisb/android-prepare-vendor/issues/38. The problem is not related to vendor generation scripts.

**Comment by anestisb** [comment]
Referencing issues has been updated with some possible workarounds.
