### ISSUE TITLE
BAD URL in scripts/download-nexus-image.sh

### ISSUE THREAD

**Issue by thierryg** [anestisb/android-prepare-vendor#43]
the GURL have been updated :

The old url and currently used in the scripts/download-nexus-image.sh script is : https://developers.google.com/android/nexus/images

The correct url is : https://developers.google.com/android/images

Indeed 'nexus' doesn't appear in the url anymore !

$ ./execute-all.sh --device bullhead --buildID MTC20K --output $(pwd)

[*] Setting output base to '/home/tgayet/_aosp-build-tests/test_bullhead_android6-vendors/bullhead/mtc20k'
[-] Image URL not found
[-] Images download failed

By fixing the url the script is working fine again : 

$ ./execute-all.sh --device bullhead --buildID MTC20K --output /home/tgayet/_aosp-build-tests/test_bullhead_android6-vendors --yes
[*] Setting output base to '/home/tgayet/_aosp-build-tests/test_bullhead_android6-vendors/bullhead/mtc20k'

--{ Google Terms and Conditions
Downloading of the system image and use of the device software is subject to the
Google Terms of Service [1]. By continuing, you agree to the Google Terms of
Service [1] and Privacy Policy [2]. Your downloading of the system image and use
of the device software may also be subject to certain third-party terms of
service, which can be found in Settings > About phone > Legal information, or as
otherwise provided.

[1] https://www.google.com/intl/en/policies/terms/
[2] https://www.google.com/intl/en/policies/privacy/

[?] I have read and agree with the above terms and conditions - ACKNOWLEDGE [y|n]: yes
[*] Downloading image from 'https://dl.google.com/dl/android/aosp/bullhead-mtc20k-factory-4a950470.zip'
--2016-11-03 11:50:05--  https://dl.google.com/dl/android/aosp/bullhead-mtc20k-factory-4a950470.zip
Résolution de dl.google.com (dl.google.com)… 216.58.204.142, 2a00:1450:4007:812::200e
Connexion à dl.google.com (dl.google.com)|216.58.204.142|:443… connecté.
requête HTTP transmise, en attente de la réponse… 200 OK
Taille : 964936536 (920M) [application/zip]
Enregistre : «/home/tgayet/_aosp-build-tests/test_bullhead_android6-vendors/bullhead/mtc20k/bullhead-mtc20k-factory-4a950470.zip»

100%[=============================================================================================================================================================================================>] 964,936,536 3.51MB/s   ds 4m 30s 

2016-11-03 11:54:35 (3.41 MB/s) - «/home/tgayet/_aosp-build-tests/test_bullhead_android6-vendors/bullhead/mtc20k/bullhead-mtc20k-factory-4a950470.zip» enregistré [964936536/964936536]

[*] Processing with 'API-23 config-naked' configuration
[*] Extracting '/home/tgayet/_aosp-build-tests/test_bullhead_android6-vendors/bullhead/mtc20k/bullhead-mtc20k-factory-4a950470.zip'
[*] Unzipping 'image-bullhead-mtc20k.zip'
[*] '20' bytecode archive files will be repaired
[*] Repairing bytecode under /system partition using oat2dex method
[*] Preparing environment for 'arm' ABI
[*] Preparing environment for 'arm64' ABI
[*] Start processing system partition & de-optimize pre-compiled bytecode
[!] '/framework/cneapiclient.jar' not pre-optimized with sanity checks passed - copying without changes
[!] '/framework/framework-res.apk' not pre-optimized & without 'classes.dex' - copying without changes
[*] '/framework/framework.jar' is multi-dex - adjusting recursive archive adds
[!] '/framework/rcsimssettings.jar' not pre-optimized with sanity checks passed - copying without changes
[!] '/framework/rcsservice.jar' not pre-optimized with sanity checks passed - copying without changes
[*] System partition successfully extracted & repaired at '/home/tgayet/_aosp-build-tests/test_bullhead_android6-vendors/bullhead/mtc20k/factory_imgs_repaired_data'
[*] Generating blobs for vendor/lge/bullhead
[*] Copying radio files '/home/tgayet/_aosp-build-tests/test_bullhead_android6-vendors/bullhead/mtc20k/vendor/lge/bullhead'
[*] Copying product files & generating 'bullhead-vendor-blobs.mk' makefile
[*] Generating 'device-vendor.mk'
[*] Generating 'AndroidBoardVendor.mk'
  [*] Bootloader:BHZ10r
  [*] Baseband:M8994F-2.6.32.1.13
[*] Generating 'BoardConfigVendor.mk'
[*] Generating 'vendor-board-info.txt'
[*] Generating 'Android.mk'
[*] Gathering data from 'vendor/app' APK/JAR pre-builts
[*] Gathering data from 'proprietary/app' APK/JAR pre-builts
[*] Gathering data from 'proprietary/framework' APK/JAR pre-builts
[*] Gathering data from 'proprietary/priv-app' APK/JAR pre-builts
[*] Generating signatures file
[*] All actions completed successfully
[*] Import '/home/tgayet/_aosp-build-tests/test_bullhead_android6-vendors/bullhead/mtc20k/vendor' to AOSP root

Because the old url is redirected to the new one, maybe we can say to curl to follow http redirection by using the -L parameter.

I have cloned the git repo on the master branch (b2ab9a3d78cf97d15019466b3fd7d5d2911245db).

BR
Thierry GAYET

**Comment by anestisb** [comment]
Fixed at https://github.com/anestisb/android-prepare-vendor/commit/2cc2dcb52d4dffb186fdb39067b748284b02d2ca

Thanks for reporting.
