### ISSUE TITLE
Pixels fail to save / restore time between reboots

### ISSUE THREAD

**Issue by thestinger** [anestisb/android-prepare-vendor#71]
The time service fails to save / restore the current time on Pixels, either due to a problem when loading it or because it's not being synced to hardware. To reproduce this, the SIM card needs to be removed and WiFi disabled to prevent the phone from syncing the time via either the mobile network or SNTP using WiFi.

If you can't reproduce this, let me know. I think it's an issue with AOSP + android-prepare-vendor but there might be some other variables.

I'm still trying to figure out what's going on... the time server seems to run and load the time, but it's always a placeholder epoch date. I can't figure out if the issue is that it's not ever setting the hardware clock but that seems like a good guess.

**Comment by thestinger** [comment]
I think it might be system/app/TimeService that's missing.

**Comment by anestisb** [comment]
I can reproduce the issue with AOSP + android-prepare-vendor for a sailfish device build against the latest tags.

Checking your fix now.

**Comment by anestisb** [comment]
Fix is also confirmed to work. Thanks.
